config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  
  get 'signup', to:'users#new'
  get 'login', to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
  resources :microposts do
    member do
      post 'retweet'
    end
    resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :users do
    member do
      get :followings, :followers, :favorites
    end
  end
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
    
    #データの保存前にメールアドレスのアルファベットを小文字にします
    before_save { self.email = self.email.downcase }
    
    #nameは空ではなく最大50文字まで
    validates :name, presence: true, length: { maximum: 50 }
    
    #メールアドレスの正規表記パターンを定義
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: { case_sensitive: false }

    has_secure_password

    #nicknameは必須ではなく最大30文字まで
    validates :nickname, length: { maximum: 30 }

    #birthdayは必須ではない
    validates :birthday, length: { maximum: 10 }
    
    
    #ユーザーは複数の投稿（マイクロポスト）を持つことができる
    has_many :microposts
    
    #ユーザーは複数のリツイートを持つことができる
    has_many :retweets

    #ユーザーは複数のリツイート（original_id）を持つことができる
    has_many :original_id
    
    
    #フォローしているユーザー
    has_many :following_relationships, class_name: "Relationship",
                            foreign_key: "follower_id",
                            dependent: :destroy
    #フォローしているユーザー一覧を受け取る                        
    has_many :following_users, through: :following_relationships, source: :followed
    
    
    #フォロアー
    has_many :follower_relationships, class_name: "Relationship",
                            foreign_key: "followed_id",
                            dependent: :destroy
    #フォロアー一覧を受け取る
    has_many :follower_users, through: :follower_relationships, source: :follower
    
    
    
    # 他のユーザーをフォローする
    def follow(other_user)
        following_relationships.find_or_create_by(followed_id: other_user.id)
    end
    
    # フォローしているユーザーをアンフォローする
    def unfollow(other_user)
        following_relationship = following_relationships.find_by(followed_id: other_user.id)
        following_relationship.destroy if following_relationship
    end
    
    
    # あるユーザーをフォローしているかどうか？
    def following?(other_user)
        following_users.include?(other_user)
    end
    
    
    #自分とフォローしているユーザーのつぶやきを取得する
    def feed_items
        Micropost.where(user_id: following_user_ids + [self.id])
    end
    
    
    
    #ユーザーは複数のお気に入りを持つことができる
    #お気に入りの一覧を取得することができる
    has_many :favorites, dependent: :destroy
    has_many :favorite_microposts, through: :favorites, source: :micropost
    
    
    
    # お気に入りに追加する
    # 現在のユーザーのfavoriteの中からお気に入りに追加するべくクリックしたmicropost_idを検索し、なかった場合新しくお気に入りを作成します。
    def favorite(micropost)
        favorites.find_or_create_by(micropost_id: micropost.id)
    end

    
    # お気に入りを削除する
    # favoriteの中から消したいmicropost_idを探し、存在する場合は削除します。
    def unfavorite(micropost)
        favorite = favorites.find_by(micropost_id: micropost.id)
        favorite.destroy if favorite
    end
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :followings, :followers, :favorites, :destroy
  ]
  before_action :check_user, only: [:edit, :update, :destroy]
  
  
  def show # ユーザーページ
  # before_action :set_userでユーザーをセットしているので下記一文は省ける
  #@user  = User.find(params[:id])
   # マイクロポストを作成日時の新しいものから順に@micropostsに代入する
   # そしてページングkaminariの代入
   @title = "Microposts"
   microposts = @user.microposts.order(created_at: :desc)
   @count = microposts.count
   @microposts = microposts.page(params[:page]).per(10)
  end
  
  
  def new
    @user = User.new
  end
  

  def destroy
    @user.destroy
    flash[:success] = "ユーザー登録を削除しました"
    redirect_to root_url #トップページにリダイレクト
  end


  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Sample App!"#フラッシュメッセージ
      redirect_to @user #新規登録後ユーザーページにリダイレクト
    else
      render 'new'
    end
  end
  
  def edit
    # before_action :set_userでユーザーをセットしているので下記一文は省ける
    # @user  = User.find(params[:id])
  end
  

  def update
    # before_action :set_userでユーザーをセットしているので下記一文は省ける
    # @user  = User.find(params[:id])
    if @user.update(user_params)
      #プロフィールの保存に成功した場合
      flash[:success] = "プロフィールを編集しました"#フラッシュメッセージ
      redirect_to @user #ユーザーページにリダイレクト
    else
    # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  #フォロー中一覧
  def followings
    # before_action :set_userでユーザーをセットしているので下記一文は省ける
    # @user  = User.find(params[:id])
    @title = "フォロー中一覧"
    users = @user.following_users
    @count = users.count
    @users = users.page(params[:page]).per(10)
    render 'show_follow'
  end
  
  #フォロワー一覧
  def followers
    # before_action :set_userでユーザーをセットしているので下記一文は省ける
    # @user  = User.find(params[:id])
    @title = "フォロワー一覧"
    users = @user.follower_users
    @count = users.count
    @users = users.page(params[:page]).per(10)
    render 'show_follow'
  end


  #お気に入り一覧
  def favorites
  # before_action :set_userでユーザーをセットしているので下記一文は省ける
    @title = "お気に入り一覧"
    microposts = @user.favorite_microposts.order(created_at: :desc)
    @count = microposts.count
    @microposts = microposts.page(params[:page]).per(10)
    render 'show'
  end






  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :nickname, :birthday)
  end
  
  
  def set_user
    @user = User.find(params[:id])
  end
  
  
  def check_user
    #アクセスした先のユーザーとログインしているユーザーが一致しない場合
    unless current_user == @user
      redirect_to root_url #トップページにリダイレクト
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
    <div id="follow_form">
        <% if current_user.following?(@user) %>
            <%= render 'unfollow' %>
        <% else %>
            <%= render 'follow' %>
        <% end %>
    </div>
<% end %>

app/views/users/_form.html.erb
    <%= form_for(@user) do |f| %>
        <!-- エラーメッセージ表示 -->
        <%= render 'shared/error_messages', object: f.object %>
    
        <%= f.label :name %>
        <span class="text-danger">*</span>
        <%= f.text_field :name, class: 'form-control' %>
        
        <%= f.label :email %>
        <span class="text-danger">*</span>
        <%= f.text_field :email, class: 'form-control' %>
        
        <%= f.label :password %>
        <span class="text-danger">*</span>
        <%= f.password_field :password, class: 'form-control' %>
        
        <%= f.label :password_confirmation, "Password confirmation" %>
        <span class="text-danger">*</span>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= render 'form_extend', f: f %>
        
        <%= f.submit([comment], class: "btn btn-primary") %>
        <!-- 変数comdmentは、edit.htmlとnew.htmlのrender内から呼び出されてボタンのラベルになる -->
    <% end %>

app/views/users/_form_extend.erb
<!-- editアクションが行われる際に下記が表示される。どこから入ってきてもいいようにアクション名をeditもupdateも両方ちゃんと書いておく -->
<% if params[:action] == 'edit' || params[:action] == 'update' %>
    <br>
    <%= f.label :nickname %>
    <%= f.text_field :nickname, class: 'form-control' %>
    
    <%= f.label :birthday %>
    <%= f.date_field :birthday, class: 'form-control' %>
<% end %>

app/views/users/_profile.html.erb
            <%= gravatar_for user %>
            <h1>
                <%= user.name %>
            </h1>
            <p>
                <span class="text-primary">ニックネーム：<%= user.nickname %></span>
            </p>
            <p>
                <span class="text-primary">生年月日：<%= user.birthday %></span>
            </p>
            
            <% if current_user == user %>
              <p>
              (<%= link_to "edit" , edit_user_path %>)
              </p>
            <% end %>
            
            <!-- フォローフォームを表示 -->
            <%= render 'follow_form' if logged_in? %>
            
            <!-- user_idがnillの場合current_userのidを入れてあげる -->
            <% user ||= current_user %>
              <div class="stats">
                <a href="<%= followings_user_path(user) %>">
                  <strong id="followings" class="stat">
                    <%= user.following_users.count %>
                  </strong>
                  following
                </a>
                <a href="<%= followers_user_path(user) %>">
                  <strong id="followers" class="stat">
                    <%= user.follower_users.count %>
                  </strong>
                  followers
                </a>
                <br>
                <a href="<%= favorites_user_path(user) %>">
                  お気に入り
                </a>
              </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
        html: {method: :delete },
        remote: true) do |f| %>
        
    <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li id="users-<%= user.id %>">
  <%= link_to gravatar_for(user, size: 50), user %>
  <span class="user">
    <%= link_to user.name, user %>
  </span>
</li>

app/views/users/edit.html.erb
<h1>Setting</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form', comment: "編集する" %>
        <!--  変数commentはsubmitボタンのラベルになる -->
        <br>
        <br>
          <%= link_to "Micropostから退会", user_path(@user), method: :delete,
                                       data: { confirm: "投稿したデータは全て消去されます。本当に退会してもよろしいですか？" }, class: "btn btn-primary" %>

        <br>
        <br>
    </div>

</div>

app/views/users/followers.html.erb
<div class="row">
    
    <aside class="col-md-4">
        <section class="user_info">
            <%= render 'profile', user: @user %>
        </section>
    </aside>
    
    <div class="col-md-8">
      <h3>フォロワー一覧(<%= @user.follower_users.count %>)</h3>
      <% @users.each do |user| %>
        <%= link_to user.name, user %>
        <br>
      <% end %>
    </div>
    
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%#= render 'form', locals: {comment: "新規登録"} %>
        <%= render 'form',comment: "新規登録" %>
        <!-- 変数commentはsubmitボタンのラベルになる -->
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
    
    <aside class="col-md-4">
        <section class="user_info">
            <%= render 'profile', user: @user %>
        </section>
    </aside>
    
    <div class="col-md-8">
        <!-- フォローフォームを表示 -->
        <%= render 'follow_form' if logged_in? %>
        
        <!-- ユーザーがマイクロポスト投稿してある場合
        投稿数を表示 -->
        <% if @user.microposts.any? %>
        <h3>Microposts (<%= @user.microposts.count %>)</h3>
        <ol class="microposts">
            <!-- 投稿を表示 -->
            <%= render @microposts %>
        </ol>
        <%= paginate @microposts %>
        <% end %>
        
    </div>
    
</div>

app/views/users/show_follow.html.erb
<div class="row">
    
    <aside class="col-md-4">
        <section class="user_info">
            <%= render 'profile', user: @user %>
        </section>
    </aside>
    
    <div class="col-md-8">


        <h3><%= @title %> (<%= @count %>)</h3>
        <ol class="users">
            <!-- 投稿を表示 -->
            <%= render @users %>
        </ol>
        <%= paginate @users %>
        
    </div>
    
</div>