config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  
  get 'signup', to:'users#new'
  get 'login', to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
  resources :microposts do
    member do
      post 'retweet'
    end
    resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :users do
    member do
      get :followings, :followers, :favorites
    end
  end
  
  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
    #投稿はそのユーザーに属する
  belongs_to :user

  #ユーザーidが存在するバリデーション
  validates :user_id, presence: true
  #コンテンツが存在し、文字数は140までのバリデーション
  validates :content, presence: true, length: { maximum: 140 }
  
  # お気に入りは複数持てて削除可能
  # お気に入りのあるユーザーをfavoriteを経由して取得する
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
  # このユーザにお気に入りが含まれていないかチェック
  # favorite_usersは上部記載のhas_many: XXXの部分
  def favorite?(user)
    favorite_users.include?(user)
  end
    
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    #ログインしたユーザーのみ投稿をクリエイト・デストロイできる
    before_action :logged_in_user, only: [:create, :destroy]
    
    
    def index
      @microposts = Micropost.includes(:user).order(created_at: :desc).limit(100).page(params[:page]).per(10)
    end
    
      def create
        @micropost = current_user.microposts.build(micropost_params)
        if @micropost.save
          flash[:success] = "Micropost created!"
          redirect_to root_url
        else
          #エラーが発生した場合はstatic_pages/homeテンプレートを使用する
          #エラーが発生した場合もページング機能を使用する
          @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page]).per(10)
          render 'static_pages/home'
        end
      end


      def retweet
        original = Micropost.find(params[:id])
        @micropost = current_user.microposts.build(original_id: original.id)
        @micropost.content = original.content
        @micropost.save
        flash[:success] = "リツイートしました"
        redirect_to request.referrer || root_url
      end
      
      
      
      def destroy
        @micropost = current_user.microposts.find_by(id: params[:id])
        return redirect_to root_url if @micropost.nil?
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to request.referrer || root_url
      end



    private
    #ストロングパラメータで受け取るデータを制限。不要なデータは受け取らない
    def micropost_params
        params.require(:micropost).permit(:content)
    end

end

app/views/microposts/_favorite.html.erb
<%= link_to "お気に入りに追加", micropost_favorites_path(micropost),
                                method: :post, remote: true, class: "btn btn-info btn-xs"  %>

app/views/microposts/_favorite_form.html.erb
<span id="favorite_form-<%= micropost.id %>">
    <% if micropost.favorite?(current_user) %>
        <%= render 'microposts/unfavorite', micropost: micropost %>
    <% else %>
        <%= render 'microposts/favorite', micropost: micropost %>
    <% end %>
</span>

app/views/microposts/_micropost.html.erb
<li id="microposts-<%= micropost.id %>">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user">
        <%= link_to micropost.user.name, micropost.user %>
        
        <% if micropost.original_id.present? %>
            （<%= link_to Micropost.find(micropost.original_id).user.name, user_path(Micropost.find(micropost.original_id).user) %>さんのリツイート）<br>
        <% end %>
        
    </span>
    
    <span class="content">
        <!-- 投稿内容 -->
        <%= micropost.content %>
    </span>
    
    <span class="timestamp">
        <!-- 投稿日時 -->
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user == micropost.user %>
            <%= link_to "投稿を削除", micropost, method: :delete, data: { confirm: "本当に消してよいですか?" }%>
        <% end %>
        <%= link_to "リツイート", retweet_micropost_path(micropost), method: :post, data: { confirm: "本当にリツイートしてもよいですか？" }, class: "btn btn-info btn-xs"  %>
        <%= render 'microposts/favorite_form', micropost: micropost %>
        
    </span>
</li>

app/views/microposts/_unfavorite.html.erb
<%= link_to "お気に入りから削除", micropost_favorites_path(micropost),
                                      method: :delete, remote: true, class: "btn btn-default btn-xs"  %>